config:
  - api/config.js

model:
  - api/model.js

router:
  - api/router.js

test:
  - test/*

kubernetes:
  - k8s/*

docker:
  - Dockerfile
  - ./*.Dokcerfile
  - docker-compose.yml

packaging:
  - package*.json

action:
  - .github/workflows/*
