config:
  - changed-files:
    - any-glob-to-any-file:
      - api/config.js

model:
  - changed-files:
    - any-glob-to-any-file:
      - api/model.js

router:
  - changed-files:
    - any-glob-to-any-file:
      - api/router.js

test:
  - changed-files:
    - any-glob-to-any-file:
      - test/*

k8s:
  - changed-files:
    - any-glob-to-any-file:
      - k8s/*

docker:
  - changed-files:
    - any-glob-to-any-file:
        - Dockerfile
        - ./*.Dokcerfile
        - docker-compose.yml

packaging:
  - changed-files:
    - any-glob-to-any-file:
      - package*.json

action:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*
