version: "3"

services:
  node:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - "./api:/app/api"
      - "./server.js:/app/server.js"
    ports:
      - "3000:3000"
    links:
      - "mongo"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
