name: DUMP
on:
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
